change every hooks README.md && CHANGELOG.md and beautify docs styles
ecomfe/react-hooks pull request #54
Opened 2020-10-30 09:44 UTC by LaughSun0513

change every hooks README.md && CHANGELOG.md 
and beautify docs styles

2020-10-30 14:54 UTC, otakustay requested changes

2020-10-30 14:54 UTC, otakustay commented on .umirc.js
> +};
js文件最后建议留一个空行吧，lint规则不会检查根目录下的那堆东西，得自己多看一眼，或者把`package.json`中的`lint`脚本改一下加上这些

2020-10-30 14:54 UTC, otakustay commented on docs/getting-started.zh-CN.md
> +
空行的使用似乎不够规范，段落之间空一行就够？而且上一行还是逗号结尾就很奇怪，可能是我遗留的问题吧

2020-10-30 14:54 UTC, otakustay commented on docs/getting-started.zh-CN.md
> +我们推荐你使用单元测试，可以把单元测试文件放在`src/__tests__`文件夹下，以`.test.js`来结尾命名，我们强烈建议你的单测覆盖率要达到100%。
这里前面空一行吧……

2020-10-30 14:54 UTC, otakustay commented on docs/getting-started.zh-CN.md
> +我们现在还没法在线上发布文档，因为`docz build`会失败，你能在每个hook的文件夹下找到`README.md`查看，或者把代码下载到本地查看，然后执行以下代码
这一段应该要改了，现在文档能发布

2020-10-30 14:54 UTC, otakustay commented on docs/index.en-US.md
> +    - text: 快速上手
既然是英文，此处是否也用英文比较合适

2020-10-30 14:54 UTC, otakustay commented on packages/action-pending/demo/useActionPending.less
> +}
同空行问题

2020-10-30 14:54 UTC, otakustay commented on packages/action-pending/demo/useActionPending.less
> +    button {
这前面得补个空行

这应该是lint功能没把`demo`目录弄进来，每个包的`package.json`里有一个`lint`脚本，默认值应该都是`skr lint`，得改成`skr lint src demo`了，可以全局搜索改一下？

2020-10-30 14:55 UTC, otakustay commented
另外我想起个事，有些包里的`demo`目录是一个完整的可运行的App，这类现在咋办？`demo`交给文档里的示例，原来的`demo`换个名字吗

2020-11-02 02:27 UTC, LaughSun0513 commented on .umirc.js
> +};
好的

2020-11-02 02:32 UTC, LaughSun0513 commented on docs/getting-started.zh-CN.md
> +我们现在还没法在线上发布文档，因为`docz build`会失败，你能在每个hook的文件夹下找到`README.md`查看，或者把代码下载到本地查看，然后执行以下代码
好的，我只是翻译了一下

2020-11-02 02:33 UTC, LaughSun0513 commented on packages/action-pending/demo/useActionPending.less
> +    button {
好，我统一改一下

2020-11-02 02:34 UTC, LaughSun0513 commented
> 另外我想起个事，有些包里的`demo`目录是一个完整的可运行的App，这类现在咋办？`demo`交给文档里的示例，原来的`demo`换个名字吗

要不换个名字？

2020-11-02 03:04 UTC, otakustay commented
> 要不换个名字？

要不原来的那些完整demo改名叫site，后续demo都用来放文档中的示例

2020-11-03 03:15 UTC, merged